const ROLES = {
  ADMIN: "Admin",
  SITE_MODERATOR: "Site Moderator",
  CLUB_OWNER: "Club Owner",
  CLUB_MODERATOR: "Club Moderator",
  CLUB_MEMBER: "Club Member",
};

const BLOCK_AFTER_UNSUCCESSFUL_LOGIN_ATTEMPTS_COUNT = 5;
const BLOCK_AFTER_UNSUCCESSFUL_LOGIN_ATTEMPTS_FOR_MINS = 15;
const RATE_LIMIT_WINDOW_SIZE_SECS = 10;
const RATE_LIMIT_REQUESTS_PER_WINDOW = 20;
const OTP_COOLDOWN_PERIOD_MINS = 5;
const OTP_VALIDITY_PERIOD_MINS = 15;

const POPULATE_FIELDS = {};

const AUTH_URL = process.env.BASEURL + `/auth/`;

const APP_CHOICES = [];

module.exports = {
  ROLES,
  APP_CHOICES,
  BLOCK_AFTER_UNSUCCESSFUL_LOGIN_ATTEMPTS_COUNT,
  BLOCK_AFTER_UNSUCCESSFUL_LOGIN_ATTEMPTS_FOR_MINS,
  RATE_LIMIT_REQUESTS_PER_WINDOW,
  RATE_LIMIT_WINDOW_SIZE_SECS,
  OTP_COOLDOWN_PERIOD_MINS,
  OTP_VALIDITY_PERIOD_MINS,
  AUTH_URL,
  POPULATE_FIELDS,
};
